import type { Metadata } from 'next'
import { ReactNode } from 'react'
import '@/../sass/main.scss'

export type LayoutProps = {
  children: ReactNode
  params: Promise<{ locale: string }>
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async (props: Readonly<LayoutProps>) => {
  const { children, params } = props
  const { locale } = await params

  // if (!hasLocale(routing.locales, locale)) {
  //   notFound()
  // }

  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
